batch_size = 4
max_epoch = 1
max_iterations = None
learning_rate = 0.001
thin_out_ratio = 0.42
data_path = './data/'
save_model = False
evaluation_freq = 2
valid_size = 0.1
test_size = 1/3
shot_sizes = [1, 2, 3, 4, 5]
min_eval_loss = 0.01
dataset_url = 'https://physionet.org/static/published-projects/mitdb/mit-bih-arrhythmia-database-1.0.0.zip'
dataset_name = 'mit-bih-arrhythmia-database-1.0.0'
